#!/usr/bin/bash
# Script for search packages from AUR
cowerinstalled=$(command -v cower 2> /dev/null)
spackage=( "$@" )
if [ ! -x "$cowerinstalled" ]; then
    printf '\e[1;31m%-6s\e[m\n' 'Please, install cower first running in your terminal:  gpg --recv-keys 1EB2638FF56C0C53 && simpleaur cower'
else
    if [ "${#spackage[@]}" -ge 0 ]; then
        cower -sc "${spackage[@]}"
    fi
fi
